spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB


app:
 datasource :
   jdbc-url : jdbc:postgresql://localhost:5432/db
   username : postgres
   password : postgres
   pool-size : 30

file:
  FDef:
    - "53eaf05e-11c6-40c7-b5ea-6337d4583e43"
    - "FDef.png"
  MDef:
    -  "358053d2-63ec-4c5d-9363-baa8f15c2a9f"
    -  "MDef.png"
  prefix: "/opt/Bonedata/"

application:
  jwt:
    secretKey: aait-ham_mbistamiMabghachikhdem
    tokenPrefix: Bearer
    tokenExpirationAfterDays: 10